export const LOAD_GIFS_START = "LOAD_GIFS_START";
export const LOAD_GIFS_SUCCESS = "LOAD_GIFS_SUCCESS";
export const LOAD_GIFS_ERROR = "LOAD_GIFS_ERROR";
export const RESET_GIFS = "RESET_GIFS";

export const LOAD_GIF_BY_ID_START = "LOAD_GIF_BY_ID_START";
export const LOAD_GIF_BY_ID_SUCCESS = "LOAD_GIF_BY_ID_SUCCESS";
export const LOAD_GIF_BY_ID_ERROR = "LOAD_GIF_BY_ID_ERROR";
export const RESET_CURRENT_GIF = "RESET_CURRENT_GIF";
